export const MONTH_THEMES = [
  {
    name: "JANUARY",
    image: "YOUR_CLOUDINARY_URL_JAN",
    accent: "#3b82f6",
    textOnImage: "#93c5fd",
  },
  {
    name: "FEBRUARY",
    image: "YOUR_CLOUDINARY_URL_FEB",
    accent: "#ec4899",
    textOnImage: "#f9a8d4",
  },
  {
    name: "MARCH",
    image: "YOUR_CLOUDINARY_URL_MAR",
    accent: "#22c55e",
    textOnImage: "#86efac",
  },
  {
    name: "APRIL",
    image: "YOUR_CLOUDINARY_URL_APR",
    accent: "#a855f7",
    textOnImage: "#d8b4fe",
  },
  {
    name: "MAY",
    image: "YOUR_CLOUDINARY_URL_MAY",
    accent: "#06b6d4",
    textOnImage: "#67e8f9",
  },
  {
    name: "JUNE",
    image: "YOUR_CLOUDINARY_URL_JUN",
    accent: "#f59e0b",
    textOnImage: "#fcd34d",
  },
  {
    name: "JULY",
    image: "YOUR_CLOUDINARY_URL_JUL",
    accent: "#ef4444",
    textOnImage: "#fca5a5",
  },
  {
    name: "AUGUST",
    image: "YOUR_CLOUDINARY_URL_AUG",
    accent: "#f97316",
    textOnImage: "#fdba74",
  },
  {
    name: "SEPTEMBER",
    image: "YOUR_CLOUDINARY_URL_SEP",
    accent: "#eab308",
    textOnImage: "#fde047",
  },
  {
    name: "OCTOBER",
    image: "YOUR_CLOUDINARY_URL_OCT",
    accent: "#ea580c",
    textOnImage: "#fdba74",
  },
  {
    name: "NOVEMBER",
    image: "YOUR_CLOUDINARY_URL_NOV",
    accent: "#78716c",
    textOnImage: "#d6d3d1",
  },
  {
    name: "DECEMBER",
    image: "YOUR_CLOUDINARY_URL_DEC",
    accent: "#6366f1",
    textOnImage: "#a5b4fc",
  },
];
export const HOLIDAYS = {
  // Fixed Date Holidays
  "0-1": "🎉 New Year's Day",
  "0-26": "🇮🇳 Republic Day",
  "3-14": "⚖️ Ambedkar Jayanti",
  "4-1": "👷 Labour Day",
  "7-15": "🇮🇳 Independence Day",
  "9-2": "👓 Gandhi Jayanti",
  "11-25": "🎄 Christmas",

  // 2026 Specific Lunar/Regional Holidays
  "0-14": "🪁 Makar Sankranti / Pongal",
  "0-15": "🌾 Magh Bihu",
  "1-15": "🔱 Maha Shivaratri",
  "2-3": "🎨 Holi",
  "2-20": "🌙 Eid-ul-Fitr",
  "3-3": "✝️ Good Friday",
  "3-15": "🌺 Rongali Bihu",
  "4-27": "🐐 Eid-ul-Adha",
  "7-28": "🪢 Raksha Bandhan",
  "8-4": "🪈 Krishna Janmashtami",
  "8-14": "🐘 Ganesh Chaturthi",
  "9-18": "🪔 Kati Bihu",
  "9-19": "🏹 Dussehra",
  "10-8": "🪔 Diwali",
  "10-10": "✨ Bhai Dooj",
  "10-24": "ੴ Guru Nanak Jayanti",
};
